#this is a guessing game
guess_number() {
    #we declear a random number and assign it to a variable called rand_number
   random_number=$((RANDOM % $1))
   #There we use a for loop, through the game
   for i in {1..2}
   do
   guest_number = $2
   #if the random number generated by the computer and that inputted by the user is thesame
     if [ $rand_number -eq $2 ]
     then
         echo "You won!"
         break
     elif [ $rand_number -gt $2 ]
     then
         echo "You missed! The random number is greater than $2"
         read -p "please try again: " guest_number
         $2 = $guest_number
     else 
         echo "You missed! The random number is lesser than $guest_number"
         read -p "please try again: " guest_number
         $2 = $guest_number
     fi   
    done
       [i -eq 3 ]; then
    echo "You lose, the number was $rand_number"
}
